# Generated by Django 2.1.2 on 2018-11-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='region',
        ),
    ]
